echo Checking if virtual environment exists...
if not exist ".\application-env\Scripts\activate.bat" (
    echo Virtual environment not found...
    echo Creating virtual environment...
    python3 -m venv application-env

    echo Activating virtual environment...
    call application-env\Scripts\activate

    echo Installing dependencies...
    pip install -r requirements.txt
) else (
    echo Virtual environment found...
    call .\application-env\Scripts\activate.bat
)

