"""Added currency column

Revision ID: 01e71d5b5eb0
Revises: a0ad5ca45c59
Create Date: 2025-05-11 00:08:23.421917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01e71d5b5eb0'
down_revision = 'a0ad5ca45c59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('finance_accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('currency', sa.String(length=3), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('finance_accounts', schema=None) as batch_op:
        batch_op.drop_column('currency')

    # ### end Alembic commands ###
