"""added finance tables

Revision ID: c28e987d9858
Revises: b720b8fdd596
Create Date: 2025-05-06 21:09:32.402541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c28e987d9858'
down_revision = 'b720b8fdd596'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('finance_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('finance_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('icon', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('finance_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['finance_accounts.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['finance_categories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('share_access_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('share_link_id', sa.Integer(), nullable=False),
    sa.Column('accessed_at', sa.DateTime(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('successful', sa.Boolean(), nullable=True),
    sa.Column('access_type', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['share_link_id'], ['shared_links.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('share_access_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_share_access_logs_share_link_id'), ['share_link_id'], unique=False)

    with op.batch_alter_table('shared_links', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('last_accessed', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('access_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('show_weight', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('show_heart_rate', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('show_activity', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('show_sleep', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('show_goals', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('show_achievements', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('one_time_password', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('password_used', sa.Boolean(), nullable=True))
        batch_op.alter_column('expires_at',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shared_links', schema=None) as batch_op:
        batch_op.alter_column('expires_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.drop_column('password_used')
        batch_op.drop_column('one_time_password')
        batch_op.drop_column('show_achievements')
        batch_op.drop_column('show_goals')
        batch_op.drop_column('show_sleep')
        batch_op.drop_column('show_activity')
        batch_op.drop_column('show_heart_rate')
        batch_op.drop_column('show_weight')
        batch_op.drop_column('access_count')
        batch_op.drop_column('last_accessed')
        batch_op.drop_column('name')

    with op.batch_alter_table('share_access_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_share_access_logs_share_link_id'))

    op.drop_table('share_access_logs')
    op.drop_table('finance_transactions')
    op.drop_table('finance_categories')
    op.drop_table('finance_accounts')
    # ### end Alembic commands ###
